### ISSUE TITLE
Why aws_access_key_id & aws_secret_access_key are hardcoded?

### ISSUE THREAD

**Issue by anshumanpattnaik** [MirceaUngureanu/dailyGrind#6]
https://github.com/MirceaUngureanu/dailyGrind/blob/c4d7924b53d56662cf2ac461c5b9067c6481f5b1/month-of-terraform/aws/credentials

The attacker can get access to internal services and unnecessary usage charges will be added to your account.

As a best practice never expose secret keys publicly on GitHub otherwise

**Comment by MirceaUngureanu** [comment]
Thanks for flagging this, not sure how that got there.
